### ISSUE TITLE
docker-compose environment not working with `with-contenv`

### ISSUE THREAD

**Issue by Nokel81** [just-containers/s6-overlay#284]
The environment variables that are listed in the `environment` section of my docker-compose file are not being propagated correctly when using s6-overlay. 

The following does work:

```yml
a-service:
  image: debian:
  command: env
  environment:
    FOOBAR: 1
    BATTLE: a string 
```

If I replace the `image` with one that has s6-overlay. And `command` with `/init` then my initial services that are in `/etc/services.d/` even when using `with-contenv` the environment variables don't get propagated through.
