### ISSUE TITLE
How to execute initialization script as root

### ISSUE THREAD

**Issue by caewok** [just-containers/s6-overlay#287]
I would like to set `ip route` in a docker container at startup, so that I can direct the network connections to a second container (for example, a VPN container). In order to do so, I need `ip route` to run as root. I can do this after the container starts by running: `dockerserviceexecprivileged ${CONTAINER} ip route add default via ${VPN_IP} dev eth1`. But I cannot figure out how to do this within the s6_overlay system.

Take, for example, the [linuxserver.io docker transmission container](https://github.com/linuxserver/docker-transmission). 

Using docker swarm, I can use the following docker compose file to add a script to the s6 overlay folder:

```
transmission:
   image: "linuxserver/transmission"
   environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - S6_READ_ONLY_ROOT=1
    configs:
      - source: changeroute_config
        target: /etc/cont-init.d/98-changeroute
        mode: 0751

##### Configs #####
configs:
  changeroute_config:
    file: ./98-changeroute
```

PUID and PGID are set to 1000 and 999, respectively. Setting S6_READ_ONLY_ROOT to 1 is because docker mounts config files read-only. 

The 98-changeroute file is simply:
```
#!/usr/bin/execlineb -P
/sbin/ip route add default via VPN_IP dev eth1 
```
Assume that __VPN_IP__ is replaced with an actual IP, such as 10.0.1.2. 

But when I run this, I get a permission error:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing... 
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing... 
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \ 
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    999
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing... 
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 98-changeroute: executing... 
> ip: RTNETLINK answers: Operation not permitted
> [cont-init.d] 98-changeroute: exited 2.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
  
My guess is that I need to escalate the privilege using either [`s6-setuidgid`](http://skarnet.org/software/s6/s6-setuidgid.html) or [`s6-sudod`](https://www.skarnet.org/software/s6/s6-sudod.html). But I cannot figure out how to accomplish that. Any suggestions would be welcome. Thanks!
