### ISSUE TITLE
container with `--pid=host` cause host services be killed

### ISSUE THREAD

**Issue by scuzhanglei** [just-containers/s6-overlay#359]
Dockerfile

```
FROM busybox
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.8.0/s6-overlay-amd64.tar.gz /tmp/
RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /
ENTRYPOINT ["/init"]
```
create a pod with `hostPID=true`，when the pod exit normally would cause services on host be killed，such as sshd。
please be careful when replay this problem on your machine as your sshd service will be killed and you can't connect you machine by ssh anymore。

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: s6
spec:
  hostPID: true
  nodeName: k8s-2
  containers:
  - name: busybox
    args: ["/bin/sh", "-c", "sleep 10"]
    image:  ${docker image build from up Dockerfile}
```
