### ISSUE TITLE
QUESTION: unable to spawn printcontenv

### ISSUE THREAD

**Issue by PriamX** [just-containers/s6-overlay#362]
Hello.

I'm not even sure if this is an s6-overlay issue, Google brought me here. 

After doing a Fedora update (and rebooting) 5 out of 15 of my docker containers provided by linuxserver.io are getting the following error and failing to boot up:

`backtick: fatal: unable to spawn printcontenv: No such file or directory`

Deleting the container and image, and redeploying makes no difference. Even tried a previous version of the container. 

The folks on linuxserver.io's Discord were at a loss, so I thought I'd ask here. Could this be related to s6-overlay, and if so, where can I start to troubleshoot?

Thanks!

**Comment by skarnet** [comment]
This sounds like an usrmerge problem with `/bin/execlineb` (which is used to interpret the `printcontenv` script) becoming unavailable. @jprjr, can you confirm? and what is an appropriate solution?

(The next version of s6-overlay, currently in testing, will solve all this, but it's not ready yet.)

**Comment by jprjr** [comment]
Can you provide an example dockerfile, and some steps to reproduce?

**Comment by PriamX** [comment]
Yes, here's one of the five, Ombi.

```
version: "2"
networks:
  plexnet:
    external:
      name: plexnet
services:
 ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=981
      - PGID=100
      - TZ=America/Denver
      - BASE_URL=/ombi #optional, for reverse proxy
    volumes:
      - /media/docker/appdata/ombi:/config
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - plexnet
    depends_on:
      - swag
    restart: unless-stopped
```
