### ISSUE TITLE
s6-linux-init: fatal: unable to copy /run/s6/basedir/run-image to /run: Operation not permitted

### ISSUE THREAD

**Issue by andersnev** [just-containers/s6-overlay#526]
Hi, 
I'm trying to run s6-overlay in a kubernetes environment with a read only filesystem and a non root user (as well as other security policies).

I suspect one of the security policies is preventing me from running s6, so I was wondering if you could help me figure out what permissions I would need to fix this error: 

```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
/package/admin/s6-overlay/libexec/preinit: info: read-only root
/package/admin/s6-overlay/libexec/preinit: info: writeable /run. Checking for executability.
s6-linux-init: fatal: unable to copy /run/s6/basedir/run-image to /run: Operation not permitted
```

I've set S6_READ_ONLY_ROOT=1, dropped privileges using the USER directive in the Dockerfile and mounted /run as a tmpfs in the container.  

Dockerfile:
```
RUN useradd -u 10001 user && \
    mkdir -p /var/run/s6/ && \
    chown -c 10001 --recursive /var/run/s6/ && \
    chown -c 10001 --recursive /run/


USER user

ENTRYPOINT ["/init"]
```

Kubernetes container and security context: 
```
      volumes:
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir:
            medium: "Memory"
      containers:
      - name: app-name
        image: image-name
        env:
          - name: "S6_READ_ONLY_ROOT"
            value: "1"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
          - name: "tmp"
            mountPath: /tmp
          - name: "run"
            mountPath: /run
```
